addons:
    apt:
        sources:
#            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-7
            - llvm-7-dev
            - g++-5
            - gcc-5
            - libboost-all-dev
            - libgtest-dev


os: linux
dist: bionic

before_install:
  - sudo pip install cmake
  - sudo wget https://github.com/google/gtest-parallel/archive/3ca6798e2c2a06708888611bc5147bd1266f97a0.zip -O gtest-parallel.zip
  - sudo mkdir gtest-parallel
  - sudo unzip -j -d gtest-parallel gtest-parallel.zip
  - sudo cp gtest-parallel/gtest_parallel.py /usr/bin/gtest_parallel.py
  # - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  # - sudo tar xf release-1.7.0.tar.gz
  # - cd googletest-release-1.7.0
  # - sudo cmake -DBUILD_SHARED_LIBS=ON .
  # - sudo make -j
  # - sudo cp -a include/gtest /usr/include
  # - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"
  - pip install --user cpp-coveralls

# Travis' clang is broken and fails to find the gold linker. Use the freshly installed one.
install:
    - if [ "$CXX" = "clang++" ]; then export CXX="/usr/bin/clang++7" CC="/usr/bin/clang-7"; fi

language: cpp

compiler:
  - clang
  - gcc

script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cd test && make -j2
  - travis_wait 30 if [ "${CXX}" = "g++" ]; then python /usr/bin/gtest_parallel.py -w 2 --print_test_times ./run_tests ; fi


after_success:
  - ls -R
  - cd CMakeFiles/run_tests.dir && coveralls --exclude /usr --gcov-options '\-lp'
